from sentence_transformers import SentenceTransformer

#Loading the model
model = SentenceTransformer("all-MiniLM-L6-v2")

def embed_text(texts):
	'''converting the text into embeddings'''
	return model.encode(texts).to_list

def get_dimension():
	'''
	To get the dimensions of the embeddings generated by the model
	'''
	return model.model.get_sentence_embedding_dimension()
